"""add updated_at to tickets

Revision ID: 4b6e71397861
Revises: 6e4915aec7fd
Create Date: 2026-09-01 12:16:11.057259

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b6e71397861"
down_revision: str | Sequence[str] | None = "6e4915aec7fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "updated_at")
    # ### end Alembic commands ###
